<?php

namespace App\Http\Resources\Admin;

use Illuminate\Http\Resources\Json\JsonResource;

class EventCreateSettingDetailResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'event_create_setting_id' => $this->event_create_setting_id,
            'language_id' => $this->language_id,
            'create_event_tab_heading' => $this->create_event_tab_heading,
            'title_label' => $this->title_label,
            'title_error' => $this->title_error,
            'country_label' => $this->country_label,
            'country_error' => $this->country_error,
            'city_label' => $this->city_label,
            'city_error' => $this->city_error,
            'street_name_label' => $this->street_name_label,
            'street_name_error' => $this->street_name_error,
            'venue_label' => $this->venue_label,
            'venue_error' => $this->venue_error,
            'product_search_label' => $this->product_search_label,
            'product_search_placeholder' => $this->product_search_placeholder,
            'product_search_error' => $this->product_search_error,
            'short_description_label' => $this->short_description_label,
            'short_description_placeholder' => $this->short_description_placeholder,
            'short_description_error' => $this->short_description_error,
            'description_label' => $this->description_label,
            'description_placeholder' => $this->description_placeholder,
            'description_error' => $this->description_error,
            'start_date_label' => $this->start_date_label,
            'start_date_error' => $this->start_date_error,
            'end_date_label' => $this->end_date_label,
            'end_date_error' => $this->end_date_error,
            'event_website_label' => $this->event_website_label,
            'event_website_placeholder' => $this->event_website_placeholder,
            'event_website_error' => $this->event_website_error,
            'exibitors_url_label' => $this->exibitors_url_label,
            'exibitors_url_placeholder' => $this->exibitors_url_placeholder,
            'exibitors_url_error' => $this->exibitors_url_error,
            'visitors_label' => $this->visitors_label,
            'visitors_placeholder' => $this->visitors_placeholder,
            'visitors_error' => $this->visitors_error,
            'press_url_label' => $this->press_url_label,
            'press_url_placeholder' => $this->press_url_placeholder,
            'press_url_error' => $this->press_url_error,
            'logo_label' => $this->logo_label,
            'logo_error' => $this->logo_error,
            'gallery_image_label' => $this->gallery_image_label,
            'gallery_image_error' => $this->gallery_image_error,
            'video_url_label' => $this->video_url_label,
            'video_url_placeholder' => $this->video_url_placeholder,
            'video_url_error' => $this->video_url_error,
            'contact_info_tab_heading' => $this->contact_info_tab_heading,
            'contact_name_label' => $this->contact_name_label,
            'contact_name_error' => $this->contact_name_error,
            'contact_email_label' => $this->contact_email_label,
            'contact_email_error' => $this->contact_email_error,
            'contact_phone_label' => $this->contact_phone_label,
            'contact_phone_error' => $this->contact_phone_error,
            'contact_designation_label' => $this->contact_designation_label,
            'contact_designation_error' => $this->contact_designation_error,
            'profile_image_label' => $this->profile_image_label,
            'profile_image_error' => $this->profile_image_error,
            'delete_btn_text' => $this->delete_btn_text,
            'add_new_contact_btn_text' => $this->add_new_contact_btn_text,
            'social_media_tab_heading' => $this->social_media_tab_heading,
            'facebook_url_label' => $this->facebook_url_label,
            'facebook_url_error' => $this->facebook_url_error,
            'twitter_url_label' => $this->twitter_url_label,
            'twitter_url_error' => $this->twitter_url_error,
            'linkedin_url_label' => $this->linkedin_url_label,
            'linkedin_url_error' => $this->linkedin_url_error,
            'youtube_url_label' => $this->youtube_url_label,
            'youtube_url_error' => $this->youtube_url_error,
            'pintrest_url_label' => $this->pintrest_url_label,
            'pintrest_url_error' => $this->pintrest_url_error,
            'instagram_url_label' => $this->instagram_url_label,
            'instagram_url_error' => $this->instagram_url_error,
            'snapchat_url_label' => $this->snapchat_url_label,
            'snapchat_url_error' => $this->snapchat_url_error,
            'terms_and_conditions_label' => $this->terms_and_conditions_label,
            'terms_and_conditions_error' => $this->terms_and_conditions_error,
            'button_text' => $this->button_text,
            'post_submit_button_text' => $this->post_submit_button_text,
            

            'event_create_setting' => new EventCreateSettingResource($this->whenLoaded('eventCreateSetting')),
        ];
    }
}
