<?php

namespace App\Http\Resources\Admin;

use Illuminate\Http\Resources\Json\JsonResource;

class RegPageSettingDetailResource extends JsonResource
{
    public function toArray($request)
    {
        return [
            'id' => $this->id,
            'reg_page_setting_id' => $this->reg_page_setting_id,
            'language_id' => $this->language_id,
            'page_title' => $this->page_title,
            'page_description' => $this->page_description,

            'greeting_text' => $this->greeting_text,
            'step_1_heading' => $this->step_1_heading,
            'step_1_acc_heading' => $this->step_1_acc_heading,
            'step_1_acc_description' => $this->step_1_acc_description,
            'step_1_description' => $this->step_1_description,
            'step_1_auto_renew_label' => $this->step_1_auto_renew_label,
            'step1_free_pkg_text' => $this->step1_free_pkg_text,
            'step1_feature_pkg_text' => $this->step1_feature_pkg_text,
            'step1_premium_pkg_text' => $this->step1_premium_pkg_text,

            'step_2_heading' => $this->step_2_heading,
            'step_2_acc_heading' => $this->step_2_acc_heading,
            'step_2_acc_description' => $this->step_2_acc_description,
            'step_2_name_label' => $this->step_2_name_label,
            'step_2_name_error' => $this->step_2_name_error,
            'step_2_name_placeholder' => $this->step_2_name_placeholder,
            'step_2_email_label' => $this->step_2_email_label,
            'step_2_email_error' => $this->step_2_email_error,
            'step_2_email_placeholder' => $this->step_2_email_placeholder,
            'step_2_password_label' => $this->step_2_password_label,
            'step_2_password_error' => $this->step_2_password_error,
            'step_2_password_placeholder' => $this->step_2_password_placeholder,
            'step_2_confirm_password_label' => $this->step_2_confirm_password_label,
            'step_2_confirm_password_error' => $this->step_2_confirm_password_error,
            'step_2_confirm_password_placeholder' => $this->step_2_confirm_password_placeholder,
            'step_2_profile_image_label' => $this->step_2_profile_image_label,
            'step_2_profile_image_placeholder' => $this->step_2_profile_image_placeholder,
            'step_2_profile_image_error' => $this->step_2_profile_image_error,

            'step_3_heading' => $this->step_3_heading,
            'step_3_acc_heading' => $this->step_3_acc_heading,
            'step_3_description' => $this->step_3_description,
            'step_3_business_categories_label' => $this->step_3_business_categories_label,
            'step_3_business_categories_error' => $this->step_3_business_categories_error,
            'step_3_business_categories_placeholder' => $this->step_3_business_categories_placeholder,

            'step_4_heading' => $this->step_4_heading,
            'step_4_acc_heading' => $this->step_4_acc_heading,
            'step_4_name_label' => $this->step_4_name_label,
            'step_4_name_error' => $this->step_4_name_error,
            'step_4_name_placeholder' => $this->step_4_name_placeholder,
            'step_4_email_label' => $this->step_4_email_label,
            'step_4_email_error' => $this->step_4_email_error,
            'step_4_email_placeholder' => $this->step_4_email_placeholder,
            'step_4_cta_link_label' => $this->step_4_cta_link_label,
            'step_4_cta_link_error' => $this->step_4_cta_link_error,
            'step_4_cta_link_placeholder' => $this->step_4_cta_link_placeholder,
            'step_4_cta_btn_label' => $this->step_4_cta_btn_label,
            'step_4_cta_btn_error' => $this->step_4_cta_btn_error,
            'step_4_cta_btn_placeholder' => $this->step_4_cta_btn_placeholder,
            'step_4_address_label' => $this->step_4_address_label,
            'step_4_address_error' => $this->step_4_address_error,
            'step_4_address_placeholder' => $this->step_4_address_placeholder,
            'step_4_phone_label' => $this->step_4_phone_label,
            'step_4_phone_error' => $this->step_4_phone_error,
            'step_4_phone_placeholder' => $this->step_4_phone_placeholder,
            'step_4_website_label' => $this->step_4_website_label,
            'step_4_website_error' => $this->step_4_website_error,
            'step_4_website_placeholder' => $this->step_4_website_placeholder,
            'step_4_short_description_label' => $this->step_4_short_description_label,
            'step_4_short_description_error' => $this->step_4_short_description_error,
            'step_4_short_description_placeholder' => $this->step_4_short_description_placeholder,
            'step_4_description_label' => $this->step_4_description_label,
            'step_4_description_error' => $this->step_4_description_error,
            'step_4_description_placeholder' => $this->step_4_description_placeholder,
            'step_4_keywords_label' => $this->step_4_keywords_label,
            'step_4_keywords_error' => $this->step_4_keywords_error,
            'step_4_keywords_placeholder' => $this->step_4_keywords_placeholder,

            'pre_media_tab_description' => $this->pre_media_tab_description,
            'step_5_heading' => $this->step_5_heading,
            'step_5_title_label' => $this->step_5_title_label,
            'step_5_title_error' => $this->step_5_title_error,
            'step_5_title_placeholder' => $this->step_5_title_placeholder,
            'step_5_description_label' => $this->step_5_description_label,
            'step_5_description_error' => $this->step_5_description_error,
            'step_5_description_placeholder' => $this->step_5_description_placeholder,
            'step_5_acc_heading' => $this->step_5_acc_heading,
            'step_5_logo_label' => $this->step_5_logo_label,
            'step_5_logo_error' => $this->step_5_logo_error,
            'step_5_logo_placeholder' => $this->step_5_logo_placeholder,
            'step_5_video_label' => $this->step_5_video_label,
            'step_5_video_error' => $this->step_5_video_error,
            'step_5_video_placeholder' => $this->step_5_video_placeholder,
            'step_5_gallery_image_label' => $this->step_5_gallery_image_label,
            'step_5_gallery_image_placeholder' => $this->step_5_gallery_image_placeholder,
            'step_5_gallery_image_error' => $this->step_5_gallery_image_error,

            'step_6_heading' => $this->step_6_heading,
            'step_6_acc_heading' => $this->step_6_acc_heading,
            'step_6_facebook_label' => $this->step_6_facebook_label,
            'step_6_facebook_error' => $this->step_6_facebook_error,
            'step_6_facebook_placeholder' => $this->step_6_facebook_placeholder,
            'step_6_twitter_label' => $this->step_6_twitter_label,
            'step_6_twitter_error' => $this->step_6_twitter_error,
            'step_6_twitter_placeholder' => $this->step_6_twitter_placeholder,
            'step_6_youtube_label' => $this->step_6_youtube_label,
            'step_6_youtube_error' => $this->step_6_youtube_error,
            'step_6_youtube_placeholder' => $this->step_6_youtube_placeholder,
            'step_6_linkedin_label' => $this->step_6_linkedin_label,
            'step_6_linkedin_error' => $this->step_6_linkedin_error,
            'step_6_linkedin_placeholder' => $this->step_6_linkedin_placeholder,
            'step_6_social_media5_label' => $this->step_6_social_media5_label,
            'step_6_social_media5_placeholder' => $this->step_6_social_media5_placeholder,
            'step_6_social_media5_error' => $this->step_6_social_media5_error,

            'terms_and_conditions_label' => $this->terms_and_conditions_label,
            'terms_and_conditions_error' => $this->terms_and_conditions_error,
            'submit_button_text' => $this->submit_button_text,
            'footer_text' => $this->footer_text,

            'reg_page_setting' => new RegPageSettingResource($this->whenLoaded('regPageSetting')),
            'language' => new LanguageResource($this->whenLoaded('language')),
        ];
    }
}
